---
- hosts: localhost
  connection: local
  vars:
    resource_group: 'RG-USEast77'
    datacenter: 'eastus'
    vm_name: 'ansiblevm77'
    vm_size: 'Standard_DS1_v2'
    username: 'weithenn'
    password: 'CentOS@77'

  tasks:
    - name: Create a Resource Group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ datacenter }}"

    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: Add Virtual Subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ vm_name }}"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vm_name }}"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create virtual network inteface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        virtual_network: "{{ vm_name }}"
        subnet: "{{ vm_name }}"
        public_ip_name: "{{ vm_name }}"
        security_group: "{{ vm_name }}"

    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ username }}"
        admin_password: "{{ password }}"
        network_interfaces: "{{ vm_name }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.7'
          version: latest