# ==================================================================
# Author:       Weithenn Wang (weithenn at weithenn.org)
# Version:      v0.1 - June 24, 2021
# Description:  Configure Cisco UCS CIMC alternate DNS to 10.10.75.12
# ==================================================================

---
- hosts: all
  gather_facts: no
  connection: local
  vars:
    cimc:
      username: '{{ CiscoUCS_username }}'
      password: '{{ CiscoUCS_password }}'

  tasks:
    - name: Configure Cisco UCS CIMC alternate DNS to 10.10.75.12
      shell: |
          sshpass -p "{{ cimc.password }}" ssh -T -o StrictHostKeyChecking=no {{ cimc.username}}@"{{ inventory_hostname }}" << EOL
          scope cimc
          scope network
          set alternate-dns-server 10.10.75.12
          commit
          y
          EOL

    - name: Pause for 30 seconds to CIMC commit
      pause:
        seconds: 30

    - name: Check Cisco UCS CIMC alternate DNS to 10.10.75.12
      shell: |
          sshpass -p "{{ cimc.password }}" ssh -T -o StrictHostKeyChecking=no {{ cimc.username}}@"{{ inventory_hostname }}" << EOL
          show cimc/network detail
          EOL
      register: check_alternate_dns

    - name: Print Cisco UCS CIMC alternate DNS
      debug:
        msg: "{{ inventory_hostname }} is {{ check_alternate_dns.stdout_lines[11] | replace('    ', '') }}"
