---
- name: Apache server installed
  hosts: apache
  become: true

  tasks:
    - name: Install apache2
      when: ansible_distribution == "Debian | Ubuntu"
      ansible.builtin.apt:
        name: apache2

    - name: Install, enalbe, start , and configure Apache
      when: ansible_distribution == "AlmaLinux"
      block:
        - name: Install Apache
          ansible.builtin.dnf:
            name: httpd

        - name: Apache enabled and running
          ansible.builtin.service:
            name: httpd
            enabled: true
            state: started

        - name: Modify listen port to 8888
          ansible.builtin.replace:
            path: /etc/httpd/conf/httpd.conf
            regexp: '^Listen 80'
            replace: 'Listen 8888'
            backup: true
          notify:
            - Restart Apache Service

  handlers:
    - name: Restart Apache Service
      ansible.builtin.service:
        name: httpd
        state: restarted
