---
- name: Fill motd file with host data
  hosts: lnode01
  become: true

  tasks:
    - name: Change motd message
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
        backup: true
